/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.paquete;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.FileReader;
import javax.swing.ImageIcon;

/**
 *
 * @author stark28
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Analizar Captura");
        jButton1.setName("btmanalizarcaptura"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    try{
                //abrir archivo y leer imagen
                String FILENAME = "/home/stark28/planos/prueba_03_03.txt";
                BufferedReader br = null;
		FileReader fr = null;
                fr = new FileReader(FILENAME);
		br = new BufferedReader(fr);
                String sCurrentLine="";
                paquete mipaquete = new paquete();
                while ((sCurrentLine = br.readLine()) != null)
                {
                    try 
                    {
                        boolean result = recuperar(br, sCurrentLine, mipaquete);
                        if (result == true)
                        {
                            result = reconstruir(br, sCurrentLine, mipaquete);
                            if (result == true)
                            {
                                System.out.println("ok: " + mipaquete.id);
                                mipaquete.insertarenbd();
                                paquete mipack = new paquete();
                                System.out.println(sCurrentLine);
                            }
                            else
                            {
                                System.out.println("emergencia: " + mipaquete.id);
                                paquete mipack = new paquete();
                            }
                        }
                        else
                        {
                            sCurrentLine = br.readLine();
                        }
                    }
                    catch(Exception ex)
                    {
                        System.out.println(ex);
                        sCurrentLine = br.readLine();
                    }
                }

                    Image im = mipaquete.restore_image();
//                    Image myImg = im.getScaledInstance(label.getWidth(), label.getHeight(),Image.SCALE_SMOOTH);
//                    ImageIcon newImage = new ImageIcon(myImg);
//                    label.setIcon(newImage);
br.close();
fr.close();
            }catch(Exception ex){
                ex.printStackTrace();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    private boolean recuperar(BufferedReader buffrd, String sLine, paquete mipaquete)
        {
            boolean isimage = false;
            try
            {
            if (mipaquete.can_start_packet(sLine))
            {
                mipaquete.set_id(sLine);
                sLine = buffrd.readLine();
                mipaquete.set_ip(sLine);
                while (!(sLine.contains("Content-Type:")))
                {
                    sLine = buffrd.readLine();    //salto lineas para buscar el tipo y la longitud del paquete
                    if (mipaquete.can_start_packet(sLine))
                    {
                        return false;
                    }
                }
                if (mipaquete.can_get_image_type(sLine))
                {
                    mipaquete.set_content_t(sLine);
                    sLine = buffrd.readLine();
                    mipaquete.set_Length_and_fragments(sLine);
                    while (!(sLine.contains("0x0000:")))
                    {
                        sLine = buffrd.readLine();    //salto lineas para buscar los bytes
                        if (mipaquete.can_start_packet(sLine))
                        {
                            return false;
                        }
                    }
                    while (mipaquete.can_start_packet(sLine) == false) //recorremos el paquete
                    {
                        if (mipaquete.can_get_image_byte(sLine) == true)
                        {
                            isimage = true;
                            mipaquete.set_init_bytes(sLine);
                            sLine = buffrd.readLine();
                        }
                        else
                        {
                            if (isimage == true)
                            {
                                mipaquete.set_bytes(sLine);
                                sLine = buffrd.readLine();
                            }
                            else
                            {
                                sLine = buffrd.readLine();
                            }
                        }
                    }
                   return true;
                }
                else
                {
                    return false;
                }
            }
            else
            {
                return false;
            }
            }
            catch (Exception ex) 
            {
             return false;   
            }
        }

                
        private boolean reconstruir(BufferedReader buffrd, String sLine, paquete mipaquete)
        {
            try
            {
            mipaquete.actual_id = mipaquete.id;
            int fragments = 1;
            while (sLine.contains(Integer.toString(mipaquete.actual_id)))
            {
                if (sLine != null && mipaquete.can_start_packet(sLine))
                {
                    if (sLine.contains(Integer.toString(mipaquete.actual_id)))
                    {
                        mipaquete.actual_id = mipaquete.actual_id + 1;
                        fragments = fragments + 1;
                        while (!(sLine.contains("0x0000:")))
                        {
                            sLine = buffrd.readLine();    //salto lineas para buscar los bytes
                        }
                        while (mipaquete.can_start_packet(sLine) == false && sLine != null) //recorremos el paquete
                        {
                            mipaquete.set_bytes(sLine);
                            sLine = buffrd.readLine();
                        }
                    }
                }
            }
            System.out.println("Los que hay: "+fragments + ". Los que son: "+ mipaquete.fragments);
            if (mipaquete.fragments == fragments)
            {
            FileOutputStream fos = new FileOutputStream("/home/stark28/Imágenes/reconstruido/"+mipaquete.id + ".jpg");
            try 
            {
                fos.write(mipaquete.HexStringToBytes(mipaquete.content_byte));
                return true;
                }
            catch(Exception e)
                    {
                        return false;
                    }
            
                finally {
                fos.close();
                }

            }
            else
            {
            FileOutputStream fos = new FileOutputStream("/home/stark28/Imágenes/reconstruido/"+mipaquete.id + ".jpg");
            try 
            {
                fos.write(mipaquete.HexStringToBytes(mipaquete.content_byte));
                return true;
                }
            catch(Exception e)
                    {
                        return false;
                    }
            
                finally {
                fos.close();
                }
            }
            }
            catch(Exception ex)
            {
                return false;
            }   
        }
}
